name: Release

on:
 push:
  tags:
   - 'v*'

jobs:
 build-windows:
  runs-on: windows-2022

  steps:
   - name: Checkout code
    uses: actions/checkout@v4

   - name: Install CMake and Ninja
    uses: lukka/get-cmake@latest

   - name: Setup vcpkg
    uses: lukka/run-vcpkg@v11
    with:
     vcpkgJsonGlob: 'vcpkg.json'

   - name: Build with CMake
    uses: lukka/run-cmake@v10
    with:
     configurePreset: 'ninja-release'
     buildPreset: 'ninja-release'

   - name: Package release
    shell: pwsh
    run: |
     New-Item -ItemType Directory -Force -Path package
     Copy-Item "build/bin/AudioCapture.exe" "package/AudioCapture.exe"
     $vcpkgRoot = $env:VCPKG_ROOT
     Copy-Item "$vcpkgRoot/installed/x64-windows/bin/opus.dll" "package/opus.dll"
     Copy-Item "$vcpkgRoot/installed/x64-windows/bin/ogg.dll" "package/ogg.dll"
     Copy-Item "$vcpkgRoot/installed/x64-windows/bin/FLAC.dll" "package/FLAC.dll"
     Copy-Item "$vcpkgRoot/installed/x64-windows/bin/FLAC++.dll" "package/FLAC++.dll"
     $tagName = "${{ github.ref_name }}"
     $zipName = "AudioCapture-$tagName-windows-x64.zip"
     Compress-Archive -Path "package/*" -DestinationPath $zipName

   - name: Create GitHub Release
    uses: softprops/action-gh-release@v2
    with:
     files: AudioCapture-*.zip
     draft: false
     prerelease: false
     generate_release_notes: false
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
